### ISSUE TITLE
Error is MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by EngUzair98** [zezo357/pytorch_lite#10]

**Comment by EngUzair98** [comment]
Thank you for your reply @zezo357. I tried it as per your suggestion but the error remains the same followed by the error "Error: Unexpected null value". Implemented the example app of yours with personally trained yolov5s optimized torchscript model with images resized to 416. Couldn't detect the root cause of the error as it gets these errors after selecting the images, especially the error "Error: Unexpected null value" occurs in runtime.

**Comment by zezo357** [comment]
May I ask what platform are you using?


But in general these steps work if package was not installed correctly

Terminate the app run
```
flutter clean 
flutter pub get
```

Also you can try 
`flutter pub upgrade `

Maybe the package that is causing the error is not updated

**Comment by EngUzair98** [comment]
I am using Android Studio, Flutter v3.3.3, and Dart SDK v2.18.2.

In addition,tried your new suggestion before, however issue remained same even updating flutter.

**Comment by zezo357** [comment]
I meant the platform you are building for is android?

**Comment by zezo357** [comment]
Also can you provide the full error

**Comment by EngUzair98** [comment]
> I meant the platform you are building for is android?

I am working on android and chrome at the same time. However, both aren't showing results.

**Comment by EngUzair98** [comment]
> Also can you provide the full error
Here's the error I receive for Chrome;

Flutter Web Bootstrap: Auto
Error is MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
Error: Unexpected null value.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/human_fall_fpds/RunModelByImageDemo.dart 84:37                                                                        runObjectDetection
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                         callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>

**Comment by zezo357** [comment]
> > Also can you provide the full error
> Here's the error I receive for Chrome;
> 
> Flutter Web Bootstrap: Auto
> Error is MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
> Error: Unexpected null value.
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
> packages/human_fall_fpds/RunModelByImageDemo.dart 84:37                                                                        runObjectDetection
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                         callback
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15               <fn>
> 

Building for the web shouldn't work, since the package is only implemented for Android for now 


Also the path provider package is not working on the web too this is why you get this error



when running on Android you get errors too? And if yes can you send it

**Comment by EngUzair98** [comment]
> > > Also can you provide the full error
> > > Here's the error I receive for Chrome;
> > 
> > 
> > Flutter Web Bootstrap: Auto
> > Error is MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
> > Error: Unexpected null value.
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
> > packages/human_fall_fpds/RunModelByImageDemo.dart 84:37                                                                        runObjectDetection
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                                         [_completeWithValue]
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                                         callback
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
> > C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15
> 
> Building for the web shouldn't work, since the package is only implemented for Android for now
> 
> Also the path provider package is not working on the web too this is why you get this error
> 
> when running on Android you get errors too? And if yes can you send it

While running on android I don't get such errors but still, the app doesn't display results. Below is the runtime results;

I/ViewRootImpl@723cb40[MainActivity](15962): ViewPostIme pointer 0
I/ViewRootImpl@723cb40[MainActivity](15962): ViewPostIme pointer 1
I/flutter (15962): Error is Unable to load asset: assets/model.pt
I/ViewRootImpl@723cb40[MainActivity](15962): ViewPostIme pointer 0
I/ViewRootImpl@723cb40[MainActivity](15962): ViewPostIme pointer 1
I/ViewRootImpl@723cb40[MainActivity](15962): MSG_WINDOW_FOCUS_CHANGED 0 1
I/ViewRootImpl@723cb40[MainActivity](15962): handleAppVisibility mAppVisible=true visible=false
I/SurfaceView@8ee04c2(15962): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} of ViewRootImpl@723cb40[MainActivity]
I/SurfaceView@8ee04c2(15962): pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@24b1e34
I/SurfaceView@8ee04c2(15962): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273}
I/BufferQueueProducer(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0#1(BLAST Consumer)1](id:3e5a00000001,api:1,p:15962,c:15962) disconnect: api 1
I/BufferQueueProducer(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0#1(BLAST Consumer)1](id:3e5a00000001,api:0,p:-1,c:15962) disconnect: api -1
I/SurfaceView@8ee04c2(15962): updateSurface: mVisible = false mSurface.isValid() = true
I/SurfaceView@8ee04c2(15962): tryReleaseSurfaces: set mRtReleaseSurfaces = true
I/SurfaceView@8ee04c2(15962): 68373688 wPL, frameNr = 0
I/SurfaceView@8ee04c2(15962): remove() from RT android.view.SurfaceView$SurfaceViewPositionUpdateListener@4134cb8 Surface(name=SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0)/@0xbe7ea91
I/SurfaceView@8ee04c2(15962): remove() io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} Surface(name=SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0)/@0xbe7ea91
I/SurfaceView@8ee04c2(15962): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@b0c7c64 fN = 0 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 android.graphics.RenderNode$CompositePositionUpdateListener.positionLost:326 
I/SurfaceView@8ee04c2(15962): aOrMT: vR.mWNT, vR = ViewRootImpl@723cb40[MainActivity]
I/ViewRootImpl@723cb40[MainActivity](15962): mWNT: t = android.view.SurfaceControl$Transaction@b0c7c64 fN = 0 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 
I/ViewRootImpl@723cb40[MainActivity](15962): mWNT: merge t to BBQ
D/OpenGLRenderer(15962): setSurface called with nullptr
D/OpenGLRenderer(15962): setSurface() destroyed EGLSurface
D/OpenGLRenderer(15962): destroyEglSurface
I/BufferQueueProducer(15962): [ViewRootImpl@723cb40[MainActivity]#0(BLAST Consumer)0](id:3e5a00000000,api:1,p:15962,c:15962) disconnect: api 1
I/BLASTBufferQueue(15962): [ViewRootImpl@723cb40[MainActivity]#0] destructor()
I/BufferQueueConsumer(15962): [ViewRootImpl@723cb40[MainActivity]#0(BLAST Consumer)0](id:3e5a00000000,api:0,p:-1,c:15962) disconnect
I/ViewRootImpl@723cb40[MainActivity](15962): Relayout returned: old=(0,0,1080,2408) new=(0,0,1080,2408) req=(1080,2408)8 dur=5 res=0x5 s={false 0} ch=true fn=33
I/SurfaceView@8ee04c2(15962): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} of ViewRootImpl@723cb40[MainActivity]
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
I/ViewRootImpl@723cb40[MainActivity](15962): stopped(true) old=false
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
D/InputTransport(15962): Input channel destroyed: 'ClientS', fd=130
I/ViewRootImpl@723cb40[MainActivity](15962): handleAppVisibility mAppVisible=false visible=true
I/SurfaceView@8ee04c2(15962): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} of ViewRootImpl@723cb40[MainActivity]
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
D/OpenGLRenderer(15962): setSurface called with nullptr
I/ViewRootImpl@723cb40[MainActivity](15962): Relayout returned: old=(0,0,1080,2408) new=(0,0,1080,2408) req=(1080,2408)4 dur=7 res=0x1 s={false 0} ch=false fn=-1
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
D/skia    (15962): SkJpegCodec::onGetPixels +
E/ion     (15962): ioctl c0044901 failed with code -1: Invalid argument
D/skia    (15962): stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7b52b9d000 length 81733
D/skia    (15962): LoadInputStreamToMem va 0x7b52b9d000  size 83968
D/libjpeg-alpha(15962): Huffman Builder run in subthread
D/libjpeg-alpha(15962): Tile Decoder (#thread:3, size:256 256 198 x496, alignment:256x16)
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Corrupt JPEG data: 10073 extraneous bytes before marker 0xc4
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/libjpeg-alpha(15962): Inconsistent progression sequence for component 0 coefficient 0
D/skia    (15962): SkJpegCodec::onGetPixels -
I/ViewRootImpl@723cb40[MainActivity](15962): stopped(false) old=true
I/ViewRootImpl@723cb40[MainActivity](15962): stopped(false) old=false
I/SurfaceView@8ee04c2(15962): onWindowVisibilityChanged(0) false io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} of ViewRootImpl@723cb40[MainActivity]
D/SurfaceView@8ee04c2(15962): updateSurface: surface is not valid
D/OpenGLRenderer(15962): setSurface called with nullptr
E/flutter (15962): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (15962): #0      _RunModelByImageDemoState.runObjectDetection (package:human_fall_fpds/RunModelByImageDemo.dart:84:35)
E/flutter (15962): <asynchronous suspension>
E/flutter (15962): 
I/BufferQueueConsumer(15962): [](id:3e5a00000002,api:0,p:-1,c:15962) connect: controlledByApp=false
I/BLASTBufferQueue(15962): [ViewRootImpl@723cb40[MainActivity]#2] constructor()
I/ViewRootImpl@723cb40[MainActivity](15962): Relayout returned: old=(0,0,1080,2408) new=(0,0,1080,2408) req=(1080,2408)0 dur=14 res=0x7 s={true -5476376622550274048} ch=true fn=-1
I/BufferQueueProducer(15962): [ViewRootImpl@723cb40[MainActivity]#2(BLAST Consumer)2](id:3e5a00000002,api:1,p:15962,c:15962) connect: api=1 producerControlledByApp=true
D/OpenGLRenderer(15962): eglCreateWindowSurface
I/SurfaceView@8ee04c2(15962): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273} of ViewRootImpl@723cb40[MainActivity]
I/BufferQueueConsumer(15962): [](id:3e5a00000003,api:0,p:-1,c:15962) connect: controlledByApp=false
I/BLASTBufferQueue(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@1#3] constructor()
I/SurfaceView@8ee04c2(15962): pST: sr = Rect(0, 0 - 1080, 2273) sw = 1080 sh = 2273
I/SurfaceView@8ee04c2(15962): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@8ee04c2(15962): pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@24b1e34
I/SurfaceView@8ee04c2(15962): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@8ee04c2(15962): updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
I/SurfaceView@8ee04c2(15962): surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273}
I/BLASTBufferQueue(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0#1] destructor()
I/BufferQueueConsumer(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@0#1(BLAST Consumer)1](id:3e5a00000001,api:0,p:-1,c:15962) disconnect
I/BufferQueueProducer(15962): [SurfaceView - com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity@8ee04c2@1#3(BLAST Consumer)3](id:3e5a00000003,api:1,p:15962,c:15962) connect: api=1 producerControlledByApp=true
I/SurfaceView@8ee04c2(15962): surfaceChanged (1080,2273) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{8ee04c2 V.E...... ........ 0,0-1080,2273}
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1375 android.view.SurfaceView.setWindowStopped:383 android.view.SurfaceView.surfaceCreated:2051 
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:599 android.view.SurfaceView.performDrawFinished:586 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] rdf()
D/ViewRootImpl@723cb40[MainActivity](15962): reportDrawFinished (fn: -1) 
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
D/ViewRootImpl@723cb40[MainActivity](15962): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
D/ViewRootImpl@723cb40[MainActivity](15962): Creating frameCompleteCallback
I/SurfaceView@8ee04c2(15962): uSP: rtp = Rect(0, 0 - 1080, 2273) rtsw = 1080 rtsh = 2273
I/SurfaceView@8ee04c2(15962): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@8ee04c2(15962): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@700dae7 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
I/SurfaceView@8ee04c2(15962): aOrMT: vR.mWNT, vR = ViewRootImpl@723cb40[MainActivity]
I/ViewRootImpl@723cb40[MainActivity](15962): mWNT: t = android.view.SurfaceControl$Transaction@700dae7 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
I/ViewRootImpl@723cb40[MainActivity](15962): mWNT: merge t to BBQ
D/ViewRootImpl@723cb40[MainActivity](15962): Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
D/ViewRootImpl@723cb40[MainActivity](15962): Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@723cb40[MainActivity](15962): [DP] rdf()
D/ViewRootImpl@723cb40[MainActivity](15962): reportDrawFinished (fn: -1) 
D/InsetsSourceConsumer(15962): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity
D/InsetsSourceConsumer(15962): ensureControlAlpha: for ITYPE_STATUS_BAR on com.example.human_fall_fpds/com.example.human_fall_fpds.MainActivity
I/ViewRootImpl@723cb40[MainActivity](15962): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(15962): startInputInner - Id : 0
I/InputMethodManager(15962): startInputInner - mService.startInputOrWindowGainedFocus

**Comment by zezo357** [comment]
Code can't find model in the path provided check that the model is in the path



Also check that you added the path to pubspec yaml assets

**Comment by EngUzair98** [comment]
> Code can't find model in the path provided check that the model is in the path
> 
> Also check that you added the path to pubspec yaml assets

Thanks, there was one model not mentioned properly in pubspec yaml assets. Anyhow, now I am getting a new error as follows for the object detection case:

E/PytorchLitePlugin( 6658): error classifying image
E/PytorchLitePlugin( 6658): java.lang.ArrayIndexOutOfBoundsException: length=74529; index=74533
E/PytorchLitePlugin( 6658): 	at com.zezo357.pytorch_lite.PrePostProcessor.outputsToNMSPredictions(PrePostProcessor.java:127)
E/PytorchLitePlugin( 6658): 	at com.zezo357.pytorch_lite.PytorchLitePlugin.getImagePredictionListObjectDetection(PytorchLitePlugin.java:245)
E/PytorchLitePlugin( 6658): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$-CC.lambda$setup$3(Pigeon.java:455)
E/PytorchLitePlugin( 6658): 	at com.zezo357.pytorch_lite.-$$Lambda$Pigeon$ModelApi$ZSJ2uOmXCh2VbE3tRuqj_ioU9XQ.onMessage(Unknown Source:2)
E/PytorchLitePlugin( 6658): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$DartMessenger$SerialTaskQueue(DartMessenger.java:163)
E/PytorchLitePlugin( 6658): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$SerialTaskQueue$F0iXMzLdPiwUET1ugdCo3vpOFvI.run(Unknown Source:2)
E/PytorchLitePlugin( 6658): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/PytorchLitePlugin( 6658): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/PytorchLitePlugin( 6658): 	at java.lang.Thread.run(Thread.java:920)

**Comment by EngUzair98** [comment]
Also, can you kindly inform, if your package works with camera stream use cases?

**Comment by EngUzair98** [comment]
Yes, my yolov5s model is optimized and I have 2 output layers, which I changed it accordingly in the app as well.

**Comment by zezo357** [comment]
From the error it's the output layer, will check to make it dynamic

**Comment by zezo357** [comment]
Can you send your model?
