### ISSUE TITLE
Can this plugin be used to make feature extraction on mobile ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [zezo357/pytorch_lite#16]
I don't want classification or object detection … what i am looking for is feature extraction with my custom model.
Is this possible here ?

**Comment by zezo357** [comment]
Do you have any android example I can follow?

**Comment by zezo357** [comment]
https://github.com/pytorch/android-demo-app from this repo

**Comment by MohamedAliRashad** [comment]
@zezo357 I don't understand

**Comment by zezo357** [comment]
> @zezo357 I don't understand

What is feature extraction, and does an example for it exist in the link above? 

If yes most probably I can implement it

**Comment by MohamedAliRashad** [comment]
@zezo357 
Feature Extraction extracts information from input image and outputs feature vector.
There is no example for it in the link you provided but it's fairly easy to implement.

I was using this [plugin](https://pub.dev/packages/pytorch_mobile) for feature extraction but it was not updated to pytorch 2.0.0 and the maintainer is not responding so i am unable to use it now. Is it possible to support a similar feature in your plugin ?

**Comment by zezo357** [comment]
So you want to input and image and get the raw output ?

**Comment by MohamedAliRashad** [comment]
Your plugin works with the latest version of PyTorch, Correct ?

**Comment by zezo357** [comment]
Yes it should, I updated to the last pytorch lite available when I was working on it.

And if not I will try to update it

**Comment by MohamedAliRashad** [comment]
You are a real hero. Thanks for the effort

**Comment by zezo357** [comment]
can you try loading the model as a classification model then running  `getImagePredictionList` on it?

it should get you the raw output from the model, i cant test it since i dont have your model

**Comment by MohamedAliRashad** [comment]
Thanks, I was able to fix my problem in the plugin i was already using (updated the pytorch version using your plugin).
@zezo357
