### ISSUE TITLE
OCR detection after detecting a bounding box

### ISSUE THREAD

**Issue by HaziqK2000** [zezo357/pytorch_lite#18]
Hello, i need to develop the license plate detection and recognition.. But i dont know which function or line that I'm supposedly modify it... The expected output is like a image attached below.. thank you so much for your help
![figure3](https://github.com/zezo357/pytorch_lite/assets/81665179/05e6ca98-3538-4d54-bf0c-c3ea86fe2d6e)

**Comment by zezo357** [comment]
i dont have an ocr functionality in this package,

**Comment by HaziqK2000** [comment]
hmm alright sir, thankyou so much
