### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by jmtrutna** [zezo357/pytorch_lite#2]
App works in android, however not in ios.  You provide a link for ios support, however I am unsure of what to do with this info...  Could you provide a little more insight as to how to get the app working in ios?

**Comment by jmtrutna** [comment]
No apologies necessary.  Thanks for clearing that up and thanks for the response.

**Comment by zezo357** [comment]
if i did implement it, will it be okay if you test it?

**Comment by FahriBilici** [comment]
I can test it if you implement it.

**Comment by jmtrutna** [comment]
Sorry for not seeing your response.  I'd be happy to help, but just fair warning, I'm far from an expert in this field lol.

**Comment by zezo357** [comment]
> Sorry for not seeing your response.  I'd be happy to help, but just fair warning, I'm far from an expert in this field lol.

The only problem is that to develop iOS support it has to be developed on Mac os which I don't have

So I am stuck until I can make another way in which I can develop it 
Or be able to make a good virtual environment run(they all are so slow and unresponsive)

So in summary there are still more tries to be done, I will try them when I can but I can't promise you anything 🥲

**Comment by zezo357** [comment]
Yes I am planning to start working on it when I finish stuff I am busy with, hope it doesn't take long

**Comment by KennyTC** [comment]
Thanks for your confirmation.
