### ISSUE TITLE
  pytorch_lite: ^3.0.0-alpha

### ISSUE THREAD

**Issue by maheralzoubi** [zezo357/pytorch_lite#20]
This is not recognized  getImagePredictionFromBytesList in last version

<img width="1440" alt="Screenshot 2023-06-11 at 5 00 14 PM" src="https://github.com/zezo357/pytorch_lite/assets/56085047/870cca2b-b289-492b-b95d-24f78d17a4bf">

**Comment by zezo357** [comment]
yes check camera example its a different logic now

**Comment by zezo357** [comment]
Keep in mind the branch for the alpha release is


 testing ffi

**Comment by maheralzoubi97** [comment]
@zezo357 
Yes, I know it is in the testing phase
 But the problem I'm having is not with the camera, it's in pytorch_lite
 See the picture
 
<img width="1440" alt="Screenshot 2023-06-11 at 5 00 14 PM" src="https://github.com/zezo357/pytorch_lite/assets/96624346/4611d90a-5d13-4fbf-832c-9a328340f3b9">
<img width="1440" alt="Screenshot 2023-06-11 at 9 52 56 PM" src="https://github.com/zezo357/pytorch_lite/assets/96624346/7e57bfa8-2d74-4a4f-b491-aec313ecefe1">

but when convert from pytorch_lite: ^3.0.0-alpha2 to pytorch_lite:      the problem disappears

**Comment by zezo357** [comment]
As I was saying this a breaking change check testing ffi camera example for the new way of handling camera

**Comment by zezo357** [comment]
```
 runClassification(Uint8List jpgBytes) async {
    if (_imageModel != null) {
      String imageClassification =
          await _imageModel!.getImagePrediction(jpgBytes);

      print("imageClassification $imageClassification");
      widget.resultsCallbackClassification(imageClassification);
    }
  }

  Future<Uint8List?> convertCameraImageToJpg(CameraImage cameraImage) async {
    Command command = Command()
      ..image(ImageUtils.processCameraImage(cameraImage)!)..encodeJpg();

    Uint8List? bytes = await command.getBytes();
    return bytes;
  }

  Future<void> runObjectDetection(Uint8List jpgBytes) async {
    if (_objectModel != null) {
      List<ResultObjectDetection?> objDetect =
          await _objectModel!.getImagePrediction(
        jpgBytes,
        minimumScore: 0.3,
        iOUThreshold: 0.3,
      );

      print("data outputted $objDetect");
      widget.resultsCallback(objDetect);
    }
  }

  /// Callback to receive each frame [CameraImage] perform inference on it
  onLatestImageAvailable(CameraImage cameraImage) async {
    if (predicting) {
      return;
    }
    predicting = true;
    Uint8List jpgBytes =(await convertCameraImageToJpg(cameraImage))!;

    var futures = <Future>[];
    futures.add(runClassification(jpgBytes));
    futures.add(runObjectDetection(jpgBytes));
    await Future.wait(futures);

    predicting = false;
  }

```

**Comment by maheralzoubi** [comment]
thanks @zezo357 
i try this code 
It has been working
I tried the version on a real phone
But when I click on the camera
Screen remains black

**Comment by zezo357** [comment]
> thanks @zezo357 
> i try this code 
> It has been working
> I tried the version on a real phone
> But when I click on the camera
> Screen remains black

As I mentioned, this is still in progress, also if you tried again it should work

**Comment by maheralzoubi** [comment]
ok i try

**Comment by maheralzoubi** [comment]
I've tried, same problem

**Comment by zezo357** [comment]
It may take sometime to fix it , I am still working on it 


But detection using images is working correctly

**Comment by zezo357** [comment]
check new release 3 

https://github.com/zezo357/pytorch_lite/tree/testing-ffi/example/lib is the example used, it should be much better since its using isolates and i did include error handling for permissions

**Comment by maheralzoubi** [comment]
Thank you for your effort
At the moment I do not have a real phone
On Sunday I will give it a go
And tell you
@zezo357

**Comment by maheralzoubi** [comment]
I tried this version
I opened the camera and a black screen did not appear
But didn't work

@zezo357

**Comment by zezo357** [comment]
> I tried this version
> I opened the camera and a black screen did not appear
> But didn't work
> 
> @zezo357 

Please share your logs,and try with version 4 and use latest code provided in the link above

**Comment by zezo357** [comment]
Also @maheralzoubi let me know what device are you testing on, and your flutter doctor output

**Comment by maheralzoubi97** [comment]
@zezo357 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64
    (Rosetta), locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
Scanning for devices is taking a long time...[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
device : iphone x

**Comment by zezo357** [comment]
> > I tried this version
> > I opened the camera and a black screen did not appear
> > But didn't work
> > 
> > @zezo357 
> 
> Please share your logs,and try with version 4 and use latest code provided in the link above 

@maheralzoubi97

**Comment by maheralzoubi** [comment]
I can't connect the real phone to the laptop
@zezo357

**Comment by zezo357** [comment]
> I can't connect the real phone to the laptop
> @zezo357 

Using an emulator won't work, they don't have camera.

This is why the camera is always black, that's not because of the package this is related to camera package.

**Comment by maheralzoubi** [comment]
No, I'm installing the app by ipa on a real phone 
But I can't connect the phone to my personal laptop
Because there is a problem with the phone

@zezo357

**Comment by zezo357** [comment]
> No, I'm installing the app by ipa on a real phone 
> But I can't connect the phone to my personal laptop
> Because there is a problem with the phone
> 
> @zezo357 

In that case I can't figure out what the problem may be, since I can't see the logs and can't replicate it

Did you use the last code in the link? It should show the error on the screen if it's a problem with the camera logic 

Can you clone the testing-ffi branch and test that example?

**Comment by maheralzoubi** [comment]
![Uploading Screenshot 2023-06-22 at 3.15.35 PM.png…]()

**Comment by maheralzoubi** [comment]
<img width="1440" alt="Screenshot 2023-06-22 at 3 15 35 @zezo357 M" src="https://github.com/zezo357/pytorch_lite/assets/56085047/ce624265-ff43-4fd1-9a0a-4b16ec81f155">
@

**Comment by zezo357** [comment]
> @zezo357 
> flutter: PytorchFfi initialization
> flutter: ImageUtilsIsolate initialization
> flutter: Error is Invalid argument(s): Failed to lookup symbol 'load_ml_model': dlsym(RTLD_DEFAULT, load_ml_model): symbol not found
> The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
> [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
> #0      _Array.[] (dart:core-patch/array.dart:10:36)
> #1      ImageUtilsIsolate.convertCameraImageToBytes
> image_utils_isolate.dart:65
> #2      _CameraViewState.onLatestImageAvailable
> camera_view.dart:195
> #3      CameraController.startImageStream.<anonymous closure>
> camera_controller.dart:469
> #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
> [log] will start prediction
> #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> #6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
> #7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
> #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
> #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> 

Thank you very much, now I know where is the problem, just a question you did flutter clean before building the app right? 

Just to make sure it's not a flutter building thing

**Comment by maheralzoubi** [comment]
@zezo357 
yes i make flutter clean

**Comment by zezo357** [comment]
<img width="900" alt="image" src="https://github.com/zezo357/pytorch_lite/assets/25157308/dfdc3b71-85b8-4ecb-9f34-e6de78bb507a">
as you can see it works correctly on the example, so i cant figure out what is the problem you are facing

**Comment by maheralzoubi** [comment]
Yes, when I upload a picture from the gallery, it works correctly
but when i real time camera show this error
@zezo357

**Comment by zezo357** [comment]
> Yes, when I upload a picture from the gallery, it works correctly
> but when i real time camera show this error
> @zezo357 

The error states that the ffi is not loaded in the case of gallery and camera they both use same logic 
Can you recheck your permissions?

**Comment by maheralzoubi** [comment]
Yes, I have checked all permissions
does not work when real time camera

@zezo357

**Comment by zezo357** [comment]
> Yes, I have checked all permissions
> does not work when real time camera
> 
> @zezo357 

Please provide logs.

**Comment by zezo357** [comment]
I have decided that it should be released since I haven't heard from you for a while, and it works as expected in my iOS simulator.

if you can provide better logs i would gladly help,
