### ISSUE TITLE
Samsung Device Bounding Box

### ISSUE THREAD

**Issue by ghilmanm** [zezo357/pytorch_lite#22]
Hi, i am using image_picker package and Samsung Device to get photos, and when i run renderBoxesOnImage. The bounding box does not match the existing object. but when i use another device, it works fine. then i try to edit image in samsung gallery and i run it again it works. is there something wrong when getting the location of the boxes? 

<img src="https://github.com/zezo357/pytorch_lite/assets/43835888/048dd8b4-5b0c-4387-99bb-8532b7651de8" height="350">
<img src="https://github.com/zezo357/pytorch_lite/assets/43835888/e433c0d1-7613-4a97-bc59-5c09cc622056" height="350">

**Comment by zezo357** [comment]
I think the problem is with the image , since after the editing the image and trying again it works right?


Can you test of the alpha release?

**Comment by zezo357** [comment]
> Yup I think the problem is also in the image, when taking a picture.  Thank u by the way for your response 
> 
> Ok, I'll test it in alpha release and I'll let you know the results later. 
> 
> in this app I use yolo v5 

Let me know when you try the alpha, it may be more stable than the current release
