### ISSUE TITLE
3.0.0+1 Run object Detection take more time about 2~3 times

### ISSUE THREAD

**Issue by ZhaoXinZhang** [zezo357/pytorch_lite#25]
Hello, I upgrade my project to pytorch_lite: ^3.0.0+1,objectDetection becomes slow(441ms -> 1676ms), it's change to use ffi instead pigeon right? 
object detection take more time and camera preview is lag ,below picture is my test with same model, can you help solve this problem? thanks.

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/7cbbc274-4496-470d-8b2c-ea6213b13d48)

**Comment by zezo357** [comment]
Looks like the inference being in ffi, didn't help in speed, I was testing on my phone and it was faster but looks like it's not the case on all phones , also there is a problem with the lag and some configuration makes the project fail, 


I do the image processing using image lib, maybe that is why it takes more time I will check if there an optimization I can do and if it will help, can you provide a repo with the logs for benchmarks (so I check if my optimization did improve the results or not )

If that didn't help, I am thinking of converting back to using platform interfaces and implement the iOS logic. 

But this may take sometime so I will work on it when I get time, you can use version 2 for now

**Comment by ZhaoXinZhang** [comment]
Hello, thanks you commented this issues.
I don't understand "can you provide a repo with the logs for benchmarks" what is it mean.
Can you tell me how can I help you, thanks.

**Comment by zezo357** [comment]
A repo with the parts of the code where you print the times of each run, I can do it but I just want to make sure it's the same as you

**Comment by ZhaoXinZhang** [comment]
Hello, both of single image detect or realtime camera have the problem.

**Comment by ZhaoXinZhang** [comment]
I will provide you " A repo with the parts of the code where you print the times of each run" later, tks.

**Comment by zezo357** [comment]
A repo with the parts of the code where you print the times of each run, I can do it but I just want to make sure it's the same as you،

Thank you, and I will check if the image processing is the problem, and I can convert it to c++.

**Comment by ZhaoXinZhang** [comment]
Helllo, this zip including two folder, the complete folder is too big to compress. So if u need more, tell me.

1. /lib folder(include pytorch_lite.dart and native_wrapper.dart which I print some thing) 
2. example/lib/ 

[issues_code.zip](https://github.com/zezo357/pytorch_lite/files/12111521/issues_code.zip)

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/fa93b461-d168-4823-8cd0-9e1403be3a26)

**Comment by zezo357** [comment]
I would like to mention that the way of s1 and s2 times are wrong


You should get the time for each one by subtraction of the start 

Like 
Before running the function get the time 
And after running the function get the time 

Then subtract the end time from the before 


And based on this the isolate is the one taking all the time, and in it I include the image processing,


I will make another branch where I test new configs and try some stuff


But all of that after I finish the cmake issues and make sure it's working for everyone

**Comment by ZhaoXinZhang** [comment]
> I would like to mention that the way of s1 and s2 times are wrong
> 
> You should get the time for each one by subtraction of the start
> 
> Like Before running the function get the time And after running the function get the time
> 
> Then subtract the end time from the before
> 
> And based on this the isolate is the one taking all the time, and in it I include the image processing,
> 
> I will make another branch where I test new configs and try some stuff
> 
> But all of that after I finish the cmake issues and make sure it's working for everyone

I know s1 and s2 time is not accurate. Because this simply test .I add the many print time everywhere in order to find the place which take most time.

So, I think the object executed time is ok to provide you check, because I didn't  tidy my test code sorry.

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/2f529eef-dd67-4b58-b036-ddf4213996af)

**Comment by zezo357** [comment]
I will try to find a way to improve and find where is it slow, and let you know what I found

**Comment by MichaelRinger** [comment]
@zezo357 What is the current average inference time for a yolov8s model with a 640x640 sized input image?

**Comment by zezo357** [comment]
> @zezo357 What is the current average inference time for a yolov8s model with a 640x640 sized input image? And I mean only pure inference without pre-/postprocessing.

will test again and let you know

**Comment by zezo357** [comment]
> @zezo357 What is the current average inference time for a yolov8s model with a 640x640 sized input image? And I mean only pure inference without pre-/postprocessing.

image_model_inference time: 186ms average while testing i was able to get around 250 ms, this is the pure inference 

keep in mind it may differ on other devices may be more or less

**Comment by zezo357** [comment]
right now decoding the image decodeImage time: 111ms takes alot of time as i mentioned, will try to find a solution for it, most probably next weekend

but i will release a patch fix where is the compile time and inference improved greatly, full  inference time was reduced by about 100 - 200 ms

**Comment by MichaelRinger** [comment]
@zezo357 Is the inference with gpu or cpu?

**Comment by zezo357** [comment]
> @zezo357 Is the inference with gpu or cpu?

cpu, pytorch doesnt extract the models using gpu, maybe in future releases they will allow it but for now only cpu

also tflite can run yolov5 and yolov8 on gpu , and the app for yolo is using tflite for the same limitation

**Comment by zezo357** [comment]
@ZhaoXinZhang can you test on 3.0.4, it should increase the performance, also i added logs for each operation time, just in case something takes more time in your device

**Comment by MichaelRinger** [comment]
> and the app for yolo(the one you can test the models with) is using tflite for the same limitation
Which limitation do you mean?

**Comment by zezo357** [comment]
> > and the app for yolo(the one you can test the models with) is using tflite for the same limitation
> 
> @zezo357 Which limitation do you mean? I already tried tflite but the tensor allocation for an 640x640 input image takes about 800ms which makes it unusable for real time usage.
> 
> 

Weird, I thought tflite should use GPU by default which make it faster 


The limition is that pytorch on mobile doesn't use GPU, the do provide how to enable it but it's not in the stable build as far as I know


I think it may get included in the 2.* Pytorch lite , meanwhile I am not sure

**Comment by MichaelRinger** [comment]
You need to pass an argument to enable inference on a gpu.  The reason why I am asking is that using yolov8 with tflite is really slow at the moment. Thats are the stats that I experienced for the yolov8n coco model:

**Phone used:** Xiaomi 11 Lite 5G NE
preprocessing:
180 ms using the flutter image library for resizing the image and a neste map loop for pixel normalization (0 - 255 -> 0 - 1)

**inference:**
800 ms tensor allocation + 450 (or 50-100 ms on gpu) ms pure inference 

postprocessing:
3 ms

**Comment by zezo357** [comment]
> You need to pass an argument to enable inference on a gpu.  The reason why I am asking is that using yolov8 with tflite is really slow at the moment. Thats are the stats that I experienced for the yolov8n coco model:
> 
> **Phone used:** Xiaomi 11 Lite 5G NE
> preprocessing:
> 180 ms using the flutter image library for resizing the image and a neste map loop for pixel normalization (0 - 255 -> 0 - 1)
> 
> **inference:**
> 800 ms tensor allocation + 450 (or 50-100 ms on gpu) ms pure inference 
> 
> **postprocessing:**
> 3 ms
> 
> 

Well, then I think this package is faster , which I thought was not the case 

Glad to hear that , you can test the package example I do include a yolov8 coco model in it, with input 640 and 640

**Comment by ZhaoXinZhang** [comment]
> @ZhaoXinZhang can you test on 3.0.4, it should increase the performance, also i added logs for each operation time, just in case something takes more time in your device

Hi, I test 3.0.4 on my device.

this is my result.

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/6d095184-9ed5-4716-ba3d-8962485c5409)

**Comment by zezo357** [comment]
> > @ZhaoXinZhang can you test on 3.0.4, it should increase the performance, also i added logs for each operation time, just in case something takes more time in your device
> 
> Hi, I test 3.0.4 on my device.
> 
> this is my result.
> 
> ![image](https://user-images.githubusercontent.com/32456820/255643537-6d095184-9ed5-4716-ba3d-8962485c5409.png)

as i thought the decode image is the one that takes most of the time

will need to figure out a way to avoid it, or offer a way to make it faster

**Comment by zezo357** [comment]
version 4.0.0 is released (which decreases decoding time)
