### ISSUE TITLE
Build failed (Version 3.0.4)

### ISSUE THREAD

**Issue by MichaelRinger** [zezo357/pytorch_lite#28]
Hello,

i am getting this error after including the package and building:

![image](https://github.com/zezo357/pytorch_lite/assets/33952961/f4787421-c710-4248-ad53-905300261eff)

Thanks for the help in advance ;)

**Comment by zezo357** [comment]
Are you using another package with this one? They are conflicting during the build process

**Comment by MichaelRinger** [comment]
@zezo357 No, there were no package conflicts during the build. I also tried installing the package on a new flutter project and the same error occured.

**Comment by zezo357** [comment]
Can you show me your pubspec? 


And the GitHub actions build works correctly, so I really need a repo to check why it fails in your case

**Comment by zezo357** [comment]
Also did you do flutter clean?

**Comment by MichaelRinger** [comment]
Flutter clean didnt help. It might be problem with my android sdk, but reinstalling the sdk didnt help as well. I am using cmake 3.18.1 and I got this error:

![image](https://github.com/zezo357/pytorch_lite/assets/33952961/70698bb9-8c76-42be-b7e8-6f792d3d32d6)

**Comment by zezo357** [comment]
Check this issue https://github.com/zezo357/pytorch_lite/issues/24

**Comment by MichaelRinger** [comment]
@zezo357 My fault, haven't seen this solved issue. Seems to work now altough with an inference of 1.0 s quite slowly for an yolov8s model.

**Comment by zezo357** [comment]
> @zezo357 My fault, haven't seen this solved issue. Seems to work now altough with an inference of 1.0 s quite slowly for an yolov8s model.

Share your inference logs, I want to know the limitations in performance in your case

**Comment by MichaelRinger** [comment]
@zezo357 Are these the correct logs?

![image](https://github.com/zezo357/pytorch_lite/assets/33952961/4c2d0b75-d2a5-40f6-a275-abb2d31a2287)

**Comment by zezo357** [comment]
Yes, looks like the model inference is slow in your device, meanwhile the decode is not slow,



Which is weird since it was the other way around in the another issue posted here

**Comment by zezo357** [comment]
version 4.0.0 is released (which decreases decoding time)

but for your case i think its limited by mobile cpu, or model size
