### ISSUE TITLE
Support streaming image from camera

### ISSUE THREAD

**Issue by dnth** [zezo357/pytorch_lite#3]
Is there any easy way to run inference on image streams from camera?

Btw, thanks for this awesome package!! Loving what you do.

**Comment by zezo357** [comment]
You can since you will get the frame bytes and pass it to the package

You may check tf lite package they had code related to converting streams to different formats 

It should work, but if you have any problems send to me and I will try to fix it 



Thank you ❤️

**Comment by dnth** [comment]
I see.. Thank you!

One more question - Can I use this with any Pytorch model that is converted to TorchScript? Is there any exception? Can it work on other tasks like image segmentation, time series, audio classification?

**Comment by zezo357** [comment]
You can run the model as classification model and process the outputs

**Comment by dnth** [comment]
Alright! I'll try it out :)

**Comment by zezo357** [comment]
> I see.. Thank you!
> 
> One more question - Can I use this with any Pytorch model that is converted to TorchScript? Is there any exception? Can it work on other tasks like image segmentation, time series, audio classification?

@dnth 
I can make other classes with their usage like the segmentation and other if they are in the [https://github.com/pytorch/android-demo-app](demo apps)

So if you need a specific feature or model just open an issue and I will try to do it

**Comment by dnth** [comment]
> > I see.. Thank you!
> > One more question - Can I use this with any Pytorch model that is converted to TorchScript? Is there any exception? Can it work on other tasks like image segmentation, time series, audio classification?
> 
> @dnth I can make other classes with their usage like the segmentation and other if they are in the https://github.com/pytorch/android-demo-app
> 
> So if you need a specific feature or model just open an issue and I will try to do it

That will be fantastic!! Segmentation is a good place to start I think

**Comment by zezo357** [comment]
> > > I see.. Thank you!
> > > One more question - Can I use this with any Pytorch model that is converted to TorchScript? Is there any exception? Can it work on other tasks like image segmentation, time series, audio classification?
> > 
> > @dnth I can make other classes with their usage like the segmentation and other if they are in the https://github.com/pytorch/android-demo-app
> > 
> > So if you need a specific feature or model just open an issue and I will try to do it
> 
> That will be fantastic!! Segmentation is a good place to start I think 

Okay I will start working on it when I have free time

**Comment by KingWu** [comment]
I tried to use this convertor to convert CameraImage to RGA format.
https://github.com/am15h/object_detection_flutter/blob/master/lib/utils/image_utils.dart

But, throw the following error. No idea how to convert CameraImage to Uint8List used with `getImagePrediction`
```
E/PytorchLitePlugin(19870): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/PytorchLitePlugin(19870): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:800)
E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.PytorchLitePlugin.getImagePredictionListObjectDetection(PytorchLitePlugin.java:205)
E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$-CC.lambda$setup$3(Pigeon.java:455)
E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
E/PytorchLitePlugin(19870): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
```

**Comment by zezo357** [comment]
> I tried to use this convertor to convert CameraImage to RGA format.
> https://github.com/am15h/object_detection_flutter/blob/master/lib/utils/image_utils.dart
> 
> I used it in this way
> ```
> var cameraImg = ImageUtils.convertCameraImage(cameraImage);
> List<ResultObjectDetection> objDetect = await _objectModel.getImagePrediction(
>     cameraImg.getBytes(),
>     minimumScore: 0.1,
>     IOUThershold: 0.3);
> ```
> 
> But, throw the following error. No idea how to convert CameraImage to Uint8List used with `getImagePrediction`
> 
> ```
> E/PytorchLitePlugin(19870): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> E/PytorchLitePlugin(19870): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:800)
> E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.PytorchLitePlugin.getImagePredictionListObjectDetection(PytorchLitePlugin.java:205)
> E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$-CC.lambda$setup$3(Pigeon.java:455)
> E/PytorchLitePlugin(19870): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$$ExternalSyntheticLambda3.onMessage(Unknown Source:2)
> E/PytorchLitePlugin(19870): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
> ```


Can you try this function instead of the getbytes?

Like imageToByteListUint8(cameraImg,512)
512 image size (change as you see fit or use camera image size)
```
  Uint8List imageToByteListUint8(img.Image image, int inputSize) { 
     var convertedBytes = Uint8List(1 * inputSize * inputSize * 3); 
     var buffer = Uint8List.view(convertedBytes.buffer); 
     int pixelIndex = 0; 
     for (var i = 0; i < inputSize; i++) { 
       for (var j = 0; j < inputSize; j++) { 
         var pixel = image.getPixel(j, i); 
         buffer[pixelIndex++] = img.getRed(pixel); 
         buffer[pixelIndex++] = img.getGreen(pixel); 
         buffer[pixelIndex++] = img.getBlue(pixel); 
       } 
     } 
     return convertedBytes.buffer.asUint8List(); 
   }
```

**Comment by KingWu** [comment]
@zezo357 Thanks for your help. I am new on machine learning. Wanna to ask a stupid question. 
I export the yolov5 file with `--img 640`. So, i need to scale the input images with 640*640 size?
Also, the input image is assumed to be a square image?

**Comment by zezo357** [comment]
> @zezo357 Thanks for your help. I am new on machine learning. Wanna to ask a stupid question. 
> I export the yolov5 file with `--img 640`. So, i need to scale the input images with 640*640 size?
> Also, the input image is assumed to be a square image?
> 

When loading the model you set the model image width and height

And the package will rescale the inputs to the model scale when making a prediction

**Comment by KingWu** [comment]
@zezo357 Thx. If i modify your code, input `width` and `height`. Is it okay?

```
Uint8List imageToByteListUint8(img.Image image, int width, int height) { 
     var convertedBytes = Uint8List(1 * width* height* 3); 
     var buffer = Uint8List.view(convertedBytes.buffer); 
     int pixelIndex = 0; 
     for (var i = 0; i < width; i++) { 
       for (var j = 0; j < height; j++) { 
         var pixel = image.getPixel(j, i); 
         buffer[pixelIndex++] = img.getRed(pixel); 
         buffer[pixelIndex++] = img.getGreen(pixel); 
         buffer[pixelIndex++] = img.getBlue(pixel); 
       } 
     } 
     return convertedBytes.buffer.asUint8List(); 
   }
```

**Comment by zezo357** [comment]
@KingWu 

I guess it will not be a problem

Keep in mind I didn't test the function due to not having a code sample 😅

I hope everything works 

Also if you have any further issues I would recommend making a new issue to make it easier for other people and I would gladly help you, thank you
