### ISSUE TITLE
version 4.0.0 The application size is very large

### ISSUE THREAD

**Issue by maheralzoubi97** [zezo357/pytorch_lite#34]
version 4.0.0 The application size is very large

**Comment by zezo357** [comment]
Was it smaller in 3*? 

I only added opencv which is 15 mb on Android and don't know the size on iOS.


Where do you say it's too large? iOS or android

**Comment by maheralzoubi97** [comment]
in android 
in version 2.0.5 size app 100 MB
in 4.0.0 size app 400 MB

**Comment by maheralzoubi97** [comment]
release

**Comment by zezo357** [comment]
setting min sdk to 24 is the main problem 

but setting         android:extractNativeLibs="true"
in android manifest reduced it to 181 mb

**Comment by zezo357** [comment]
upon further checking, the problem is related to torch version, since https://github.com/zezo357/pytorch_lite/pull/42 uses same logic as version 2 but the torch version is the latest 

and the apk size is 168mb

**Comment by zezo357** [comment]
most probably fixed in 4.2.0 , check and let me know
