### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'load_ml_model': dlsym(RTLD_DEFAULT, load_ml_model): symbol not found

### ISSUE THREAD

**Issue by tnghieu** [zezo357/pytorch_lite#36]
When using
`await PytorchLite.loadClassificationModel(
        "assets/models/best.pt",
        640,
        480,
        9,
        labelPath: "assets/labels/labels.txt",
      );`

**Comment by zezo357** [comment]
What platform are you testing on, 

Also did you close the app and rebuild it after adding the package?

**Comment by tnghieu** [comment]
iOS

Yes, I also tried cleaning and removing the podfile.

**Comment by zezo357** [comment]
I will try to test, but can you provide an example repo? Or configuration since my integration tests work

**Comment by tnghieu** [comment]
https://github.com/tnghieu/sharkeye

**Comment by zezo357** [comment]
Hello, thank you for the repo, sadly I am not available this week

**Comment by tnghieu** [comment]
Hi @zezo357, I've made updates and used the export to torchscript and I am still seeing the same error. Is this compatible with iOS?

**Comment by zezo357** [comment]
Using my GitHub actions, yes it works on both iOS and Android


I will need more details, like the version you are using in pubspec

Flutter doctor -v

**Comment by tnghieu** [comment]
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] Network resources

pytorch_lite: ^4.0.0

My repo has latest changes with the model weights.

**Comment by zezo357** [comment]
Thank you, can you wait for next weekend? Since I can't try now as I mentioned

**Comment by tnghieu** [comment]
Yes I can wait. Thank you for your time.

**Comment by zezo357** [comment]
been trying for a while the only solution i found is to add the cpp file in Compile Source in xcode

which is a very bad workaround since whenever i update the package you will have to update it 


so i am thinking of going back to native 

* Think this will fix the large size on both android and ios
* Having good speed since it will use native ways to handle images

i will try to maintain new interface and just change the back logic 

sadly it may take sometime to completely migrate back and add the ios logic since i dont understand obj c or swift 

sorry for the inconvenience and if i can help with something else let me know 

btw loved the idea of your project simple and does the job very good

**Comment by tnghieu** [comment]
Thank you. I look forward to the updates.

**Comment by tnghieu** [comment]
Hi @zezo357 , I see you've made a new update/PR. Thank you for the work!

I do have a question - does this library support object detection models? I ask because google-ml-object-detection library in Flutter can only use custom image classification models.

**Comment by zezo357** [comment]
> Hi @zezo357 , I see you've made a new update/PR. Thank you for the work!
> 
> I do have a question - does this library support object detection models? I ask because google-ml-object-detection library in Flutter can only use custom image classification models.

yolov5 and yolov8 are supported yes

**Comment by zezo357** [comment]
please check version `https://pub.dev/packages/pytorch_lite/versions/4.1.0-dev`

camera code is tested on android but not tested on ios hopefully it works (will need someone to test it and report its status)

**Comment by zezo357** [comment]
Fixed in 4.2.0
