### ISSUE TITLE
Build failed in version 4

### ISSUE THREAD

**Issue by ZhaoXinZhang** [zezo357/pytorch_lite#37]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pytorch_lite:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\zhaox\AppData\Local\Pub\Cache\hosted\pub.dev\pytorch_lite-4.0.0\android\.cxx\Debug\4m244l20\arm64-v8a'
  [1/1] Linking CXX shared library D:\Project\Flutter\instai2\build\pytorch_lite\intermediates\cxx\Debug\4m244l20\obj\arm64-v8a\libpytorch_lite.so
  FAILED: D:/Project/Flutter/instai2/build/pytorch_lite/intermediates/cxx/Debug/4m244l20/obj/arm64-v8a/libpytorch_lite.so 
  cmd.exe /C "cd . && C:\Users\zhaox\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=C:/Users/zhaox/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/zhaox/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fopenmp -static-openmp -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libpytorch_lite.so -o D:\Project\Flutter\instai2\build\pytorch_lite\intermediates\cxx\Debug\4m244l20\obj\arm64-v8a\libpytorch_lite.so CMakeFiles/pytorch_lite.dir/C_/Users/zhaox/AppData/Local/Pub/Cache/hosted/pub.dev/pytorch_lite-4.0.0/ios/Classes/pytorch_ffi.cpp.o  ../../../../libtorch-android-13.1/libtorch-android-13.1/jni/arm64-v8a/libc++_shared.so  ../../../../libtorch-android-13.1/libtorch-android-13.1/jni/arm64-v8a/libfbjni.so  ../../../../libtorch-android-13.1/libtorch-android-13.1/jni/arm64-v8a/libpytorch_jni.so  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_core.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_features2d.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_highgui.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_photo.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_video.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a  ../../../../opencv/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_core.a  -ldl  -lm  -llog  -latomic -lm && cd ."
`

flutter doctor -v
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3324],
    locale en-US)
    • Flutter version 3.13.2 on channel stable at D:\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (12 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\zhaox\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)      
    • All Android licenses accepted.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

**Comment by ZhaoXinZhang** [comment]
maybe is because ndk version lead to build failed

**Comment by ZhaoXinZhang** [comment]
It is lack file here?

![image](https://github.com/zezo357/pytorch_lite/assets/32456820/485efd42-9153-4923-877d-3ac5fcc3cbe8)

**Comment by ZhaoXinZhang** [comment]
Hi I think the problem is 
dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        // classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}

when com.android.tools.build:gradle:7.3.0 will build failed ,I change to classpath 'com.android.tools.build:gradle:7.1.2', it fix.
Is that a problem?

**Comment by zezo357** [comment]
Changing the Gradle version fixes the issue yes

**Comment by ZhaoXinZhang** [comment]
Same as #24 right?

**Comment by zezo357** [comment]
Yes, why? 

If you can provide a pr explaining it in readme, that's will be awesome

**Comment by ZhaoXinZhang** [comment]
OK,I do it .

**Comment by zezo357** [comment]
please check version `https://pub.dev/packages/pytorch_lite/versions/4.1.0-dev`

camera code is tested on android but not tested on ios hopefully it works (will need someone to test it and report its status)

no need for ndk version now, thank you for pr but it wont be needed now
