### ISSUE TITLE
Could not run on a real device

### ISSUE THREAD

**Issue by dnth** [zezo357/pytorch_lite#4]
I tried exporting the example app into an APK to run it on a real device. But I found that the images will not load when I click on the buttons.

Everything works on an Android emulator.

Is there a special permission needed to run on a real device?

**Comment by zezo357** [comment]
Android device?

I will re check permissions and test it

**Comment by dnth** [comment]
Yes Android device

**Comment by zezo357** [comment]
It should work now as expected 

you can download the updated code and try again


thank you for letting me know ♥

**Comment by dnth** [comment]
Cool! I'll try it and get back. Thanks a lot buddy!

**Comment by dnth** [comment]
Perfect! It works now!
