### ISSUE TITLE
issue when run_model_by_image

### ISSUE THREAD

**Issue by maheralzoubi97** [zezo357/pytorch_lite#45]
Exception caught by widgets library ═══════════════════════════════════
The following LateError was thrown building RunModelByImageDemo(dirty, state: _RunModelByImageDemoState#b79a5):
LateInitializationError: Field '_objectModel@321402722' has not been initialized.

The relevant error-causing widget was
RunModelByImageDemo

**Comment by zezo357** [comment]
there is an error, you didnt share, please share full logs ,and what version are you testing on

**Comment by zezo357** [comment]
most probably fixed in 4.2.0
