### ISSUE TITLE
Pytorch Issues

### ISSUE THREAD

**Issue by tnghieu** [zezo357/pytorch_lite#46]
I'm on the latest 4.2.0+2

The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo/___torch_mangle_1054.py", line 80, in forward
    input31 = torch.silu_(_38)
    _39 = torch.upsample_nearest2d(input31, None, [2., 2.])
    input32 = torch.cat([_39, input20], 1)
              ~~~~~~~~~ <--- HERE
    _40 = ops.prepacked.conv2d_clamp_run(input32, CONSTANTS.c34)
    _41 = ops.prepacked.conv2d_clamp_run(input32, CONSTANTS.c35)


Traceback of TorchScript, original code (most recent call last):
/Users/me/github_repos/yolov5/models/common.py(324): forward
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/nn/modules/module.py(1501): _call_impl
/Users/me/github_repos/yolov5/models/yolo.py(121): _forward_once
/Users/me/github_repos/yolov5/models/yolo.py(209): forward
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/nn/modules/module.py(1501): _call_impl
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/jit/_trace.py(1056): trace_module
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/jit/_trace.py(794): trace
/Users/me/github_repos/yolov5/export.py(141): export_torchscript
/Users/me/github_repos/yolov5/export.py(125): outer_func
/Users/me/github_repos/yolov5/export.py(768): run
/Users/me/github_repos/yolov5/yoloEnv/lib/python3.9/site-packages/torch/utils/_contextlib.py(115): decorate_context
/Users/me/github_repos/yolov5/export.py(858): main
/Users/me/github_repos/yolov5/export.py(863): <module>
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
PytorchLitePlugin result length before processing 0
PytorchLitePlugin result length after processing 0

I am using object detection and testing it on a single image.

*** SETUP ***
objectModel = await PytorchLite.loadObjectDetectionModel(
        "assets/models/weights640.torchscript",
        1,
        640,
        318,
        labelPath: "assets/labels/sharklabel.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov5,
      );
      
*** Execution ***
 var x = (await rootBundle.load('assets/labels/sharkpic.jpg'))
            .buffer
            .asUint8List();

        List<ResultObjectDetection> res =
            await objectModel.getImagePrediction(x);

**Comment by tnghieu** [comment]
My coworker is generating a .pt weights file made from a yoloV5 object detection model. 

What's the best use of this library? I'm assuming it's using the PytorchLite.loadObjectDetectionModel().

I've tried both the .pt and the exported .torchscript versions and they don't work as the model to load.

**Comment by zezo357** [comment]
!python export.py --weights "the weights of your model" --include torchscript --img 640 --optimize

this is using yolov5 repo
for example

**Comment by tnghieu** [comment]
Yes I used that to convert the .pt to torch script.

**Comment by zezo357** [comment]
That's weird the model I have works, and I am using latest version of pytorch mobile, maybe because it's a pytorch v2 model?

**Comment by tnghieu** [comment]
What does 640 represent in the --img flag? Height or Width? 

If my images are 640 width by 480 height, what should I use?

Also for Model setup as well:
`
await PytorchLite.loadObjectDetectionModel(
      "assets/models/weights1280.torchscript",
      1,
      640,
      640,
      labelPath: "assets/labels/sharklabel.txt",
      objectDetectionModelType: ObjectDetectionModelType.yolov5,
);
`

**Comment by tnghieu** [comment]
Thanks, I have it working now. The issue was with these dimensions. Closing this.
