### ISSUE TITLE
real-time detection slow

### ISSUE THREAD

**Issue by maheralzoubi97** [zezo357/pytorch_lite#47]
Why is the real-time detection slow compared to the native?

**Comment by zezo357** [comment]
@maheralzoubi97 You can change the preprocessing method, and pick whatever fits your use case, 


It's explained in which one uses what, 



And for performance testing please try on profile, release modes 
To ensure the best speed

**Comment by JobiJoba** [comment]
Hi @zezo357, 

I'm running the example of this project in release mode and have quite a high inference time for the object detection. 

Do you have the same result or have a better inference time? 

Any idea why this is happening.  Thanks

![42406](https://github.com/zezo357/pytorch_lite/assets/6494791/4f431376-1856-46b1-8333-ba48c59e9410)

**Comment by zezo357** [comment]
Can you try with preprocessing method as native,

**Comment by JobiJoba** [comment]
How do you do that?

**Comment by JobiJoba** [comment]
My bad, I just saw the parameters. Let me check :)

**Comment by JobiJoba** [comment]
argh I see :) thank you with a low camera setting I can reach 4/5 fps. 
And Also using a lower image resolution model.
