### ISSUE TITLE
Is there a way to run object detection on rectangular shaped videos?

### ISSUE THREAD

**Issue by jackrogers47** [zezo357/pytorch_lite#49]
I am trying to run object detection on 360p (640x360 pixels) video. When making the call to run inference: 

`objectDetectionModel = await PytorchLite.loadObjectDetectionModel(
        "assets/models/speed_test_640.torchscript",
        1,
        640,
        640,
        labelPath: "assets/labels/labels.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov5,
      );`

image width and height are parameters of loadObjectDetectionModel(), but it errors whenever I pass width and height arguments that are not the same number (640, 360). It will run when width and height are the same number (640, 640) but detections are inaccurate and slow as I think it stretches the frames to fit the 640x640 parameters. 

Is there any way to run object detections on rectangularly shaped inputs with this library? Thanks for your work on this library and thanks in advance for your reply!

**Comment by zezo357** [comment]
You model input is 640 640 so a width and height different than that will not work 


For speed please try to test on profile or release since they will be faster 

Or try the to set the preprocessing method to be native which is faster, but can be slightly  different between iOS and Android

**Comment by jackrogers47** [comment]
sorry, for clarification:

our input video is 640x360 p

when we run:

`objectDetectionModel = await PytorchLite.loadObjectDetectionModel(
        "assets/models/speed_test_640.torchscript",
        1,
        640,
        360,
        labelPath: "assets/labels/labels.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov5,
      );`

we get an error message saying:

`RuntimeError: The size of tensor a (40) must match the size of tensor b (80) at non-singleton dimension 2`



when we run:

`objectDetectionModel = await PytorchLite.loadObjectDetectionModel(
        "assets/models/speed_test_640.torchscript",
        1,
        640,
        640,
        labelPath: "assets/labels/labels.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov5,
      );`

our program executes but stretches the input images to a square resulting in inaccurate detections. Wondering if there is any way for the library to run inference on rectangular-shaped images.

**Comment by zezo357** [comment]
You object detections model is the limition, it's input size is 640x640 so the code stretches it to be able to fit in the model input size


If your model input is the same as the input you want to use it will work 


Also why the boxes are not accurate the widget should scale correctly to fit any view

**Comment by jackrogers47** [comment]
Thank you so much. I think yolov5 does allow for you to detect on rectangular images. Is there another place to specify model input to make it work?

**Comment by zezo357** [comment]
You will need to export your model with the input size as whatever you would like, then you can use it in like how you did before

**Comment by jackrogers47** [comment]
Still having trouble running inference on rectangular-shaped images. Our goal is to run inference on 384p x 640p images with a custom-trained yolov5 object detection model.

We export our model with the input dims 384, 640. See the attached photo for export.

<img width="895" alt="Screenshot 2023-10-19 at 6 10 58 PM" src="https://github.com/zezo357/pytorch_lite/assets/78061189/15eb370b-8193-4fab-a094-53a80aa054e0">


we initialize our model with:

`objectDetectionModel = await PytorchLite.loadObjectDetectionModel(
        "assets/models/speed_test_640.torchscript",
        1,
        640,
        384,
        labelPath: "assets/labels/labels.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov5,
      );`

and confirm the dimensions of our input video are 384x640.

When running inference we receive the following error message: 

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSFrozenArrayM objectAtIndexedSubscript:]: index 90724 beyond bounds [0 .. 90719]'
*** First throw call stack:
(0x1980f8cb4 0x19118c3d0 0x19829ef84 0x198118bfc 0x10261557c 0x10261623c 0x1026199c4 0x1026124a8 0x10b5e1574 0x10b039480 0x19f5be320 0x19f5bfeac 0x19f5c7534 0x19f5c80a4 0x19f5d2cdc 0x1f7f29ddc 0x1f7f29b7c)`

Unsure of where to go from here. Thank you for any advice.

**Comment by jackrogers47** [comment]
goal dimensions are 640p width 384p height.

**Comment by JobiJoba** [comment]
Hey @jackrogers47 , not sure if this can help but you can maybe try. 

I used another model size (512x512 and 320x320) and i had to change the mOutputRow inside the java code itself (like here : https://github.com/zezo357/pytorch_lite/commit/d1932079e8aa21e49f26b18db802946a83325946 )

There was a formula to determine the mOutputRow depending on the size

**Comment by zezo357** [comment]
Thank you for pointing this point, I will check if there is a way to make it dynamic to allow for more models shapes , since having to change the java file and objc ones for each model shape is not ideal

**Comment by JobiJoba** [comment]
yeah sorry, not an expert on how those stuff is done, so I did a very quick dirty way :)

**Comment by zezo357** [comment]
> yeah sorry, not an expert on how those stuff is done, so I did a very quick dirty way :) 

It's okay, thank you for letting us know, at least now we can think of a way to make it easier for other people, 


Btw I just checked the android repo for pytorch, and there is open issue and 2 related with no fix , so hopefully I figure something out 😢

**Comment by zezo357** [comment]
hello @jackrogers47 @JobiJoba 
can you test on this version `pytorch_lite: ^4.2.1-beta`

if all is well i will release it, if there is a problem let me know so i fix it before releasing

**Comment by jackrogers47** [comment]
Will do, thank you!!

**Comment by jackrogers47** [comment]
Apologies for the late response, but it worked! Thank you so much

**Comment by jackrogers47** [comment]
We are currently only able to run inference on images after extracting images from a video, is there a way to run inference directly on a video file without sampling images from it?

**Comment by zezo357** [comment]
Sadly I don't have a way to do so.

And don't think I have the time and knowledge to implement it

**Comment by jackrogers47** [comment]
No worries, thank you anyways. you have been a ton of help so far

**Comment by zezo357** [comment]
Glad to help, and don't hesitate to let me know if there is anything else.

I will close this issue since it was fixed.
