### ISSUE TITLE
Object Tracking / Unique detections

### ISSUE THREAD

**Issue by tnghieu** [zezo357/pytorch_lite#50]
I'm using pytorch_lite to run inference on image frames extracted from a video file.

From a single image, I know that the library will return a list of detections given a certain confidence threshold.

Do you have an approach such that at the end of running inference across all of the images, it can output the total unique objects tracked? We are only using 1 label and our goal is to count the number of that object seen in the video.

**Comment by zezo357** [comment]
Nothing is provided by default here, you will have to implement the logic for that
