### ISSUE TITLE
dont work classification

### ISSUE THREAD

**Issue by alibeknakhimov** [zezo357/pytorch_lite#59]
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torch.load('best.pt',map_location="cpu")
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("model.pt")

when i use this code for optimize for mobile it has error
--------------------------------------------------------------------------------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-84e324efbbf3>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 model = torch.load('best.pt',map_location="cpu")
----> 6 model.eval()
      7 example = torch.rand(1, 3, 224, 224)
      8 traced_script_module = torch.jit.trace(model, example)

AttributeError: 'dict' object has no attribute 'eval'
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by zezo357** [comment]
how did you save the model? can you provide the training and saving code (just an example)

**Comment by alibeknakhimov** [comment]
i trained model with yolov5

!python train.py --img 640 --batch 32 --epochs 300 --data coco128.yaml --weights yolov5s.pt --cache

and after i took best.pt file from dir runs/train/exp/weights/best.pt and used this code
model = torch.load('best.pt',map_location="cpu")
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("model.pt")

**Comment by zezo357** [comment]
for yolov5 its an object detection model btw?


and in the readme the export method is  

`!python export.py --weights "the weights of your model" --include torchscript --img 640 --optimize`

**Comment by alibeknakhimov** [comment]
i did the same but it too dont work. it launching but dont find object

**Comment by zezo357** [comment]
test you model with `!python detect.py --weight 'path to exported model' --source `
if that shows no object then its the model itself that has a problem, if it does show an object let me know, will check what can be done since there is another issue related to this point 


also please provide screenshot if it does show objects  (one from app, and one from the detect.py)

**Comment by alibeknakhimov** [comment]
i did it!!!!!!!!!!!!!!! you are awesome. is it support for ios?

**Comment by zezo357** [comment]
Yes iOS is supported

**Comment by alibeknakhimov** [comment]
thanks!!!!!

**Comment by zezo357** [comment]
you are welcome, glad to help <3
