### ISSUE TITLE
Mobile Classification Conversion issues. 

### ISSUE THREAD

**Issue by WesleyFrancis** [zezo357/pytorch_lite#60]
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torch.load('model_scripted.pt',map_location="cpu")
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("model.pt")

The script provided in the example to convert a classification model doesn't seem to work atleast on colab. The following is the error 
I'm getting. 
ModuleNotFoundError: No module named 'ultralytics.yolo' 

converting the classification to torchscript directly produces a classification model that's wildly inaccurate.

**Comment by zezo357** [comment]
Please provide full code and model so I can help,

ModuleNotFoundError: No module named 'ultralytics.yolo'

This error is related to packages not being imported

**Comment by WesleyFrancis** [comment]
All I did was copy paste the classification section of preparing the model and  gave this file as the input. It's a character classifier. 
[yolov8s_char_classifier.zip](https://github.com/zezo357/pytorch_lite/files/13199045/yolov8s_char_classifier.zip)

**Comment by zezo357** [comment]
It's a yolo classifier model? Did you try the export from yolo?

**Comment by zezo357** [comment]
like this `!yolo mode=export model="your model" format=torchscript optimize`

**Comment by WesleyFrancis** [comment]
orr.. we were supposed to export the classifier models aswell in torchscript format? I thought the classifier was using the .pt file. In that case I can ignore that step and just export it normal from yoolov8 as documented.

**Comment by zezo357** [comment]
all the models can be used in torchscript format yes

**Comment by WesleyFrancis** [comment]
Thanks..
