### ISSUE TITLE
Does pytorch_lite work on iOS 12?

### ISSUE THREAD

**Issue by andynewman10** [zezo357/pytorch_lite#63]
Based on this thread:

https://github.com/pytorch/pytorch/issues/102833

- it is unclear whether LibTorch 1.13 actually works or not on iOS 12.
  - Two users say it is not working, but one user says it is working fine (see this post: https://github.com/pytorch/pytorch/issues/102833#issuecomment-1820125165).
  - the author of the above mentionned post also described the problem here: https://forums.swift.org/t/swift-concurrency-back-deploy-issue/53917/32
- LibTorch 2.1.0, which has been released (I don't know where to grab it from?) does not seem functional on iOS 12, according to the same user.

**Comment by zezo357** [comment]
For now I think will need someone with iOS 12 to test package to make sure if it works or not, I don't have an iOS device 😕
