### ISSUE TITLE
Unable to dynamically load model file 

### ISSUE THREAD

**Issue by fixatd** [zezo357/pytorch_lite#69]
I'm working on an application where I store the model file (`torchscript` file) in the cloud and load it dynamically however I keep getting errors when I try to do so. It works fine when it's from the local assets folder.

Based from the `_getAbsolutePath` method, it's only going to load files declared as an asset:

```dart
  static Future<String> _getAbsolutePath(String path) async {
    Directory dir = await getApplicationDocumentsDirectory();
    String dirPath = join(dir.path, path);
    ByteData data = await rootBundle.load(path);
    // Rest of the code 
}
```

Are there any plans to allow loading the model file dynamically ?

**Comment by zezo357** [comment]
The loading method requires loading from path, I didn't try loading bytes  before 


If you would like to add a pr, let me know but I will check it when I have some free time

**Comment by fixatd** [comment]
I have tried loading downloaded files but it seems like it's not allowed, I kept getting the following error:

```
[log] Error is Unable to load asset: "/data/user/0/****************/app_flutter/downloads/6f10fa8e-e09c-46ac-baa1-6fb8e166d15d_log-detection-v2.torchscript".
      The asset does not exist or has empty data.
```

I've tried providing the full path for the model file and also the relative path to `getApplicationDocumentsDirectory()` but still seems to give me the same error.

**Comment by zezo357** [comment]
Looks like get absolute path tries to get it from asset each Time, will see what can be done

**Comment by fixatd** [comment]
Yes, a bit curious as I was reading through `_getAbsolutePath()` and it seems to copy the model file into another directory. Though that being said, it looks like both the model and the labels are only allowed to be loaded from the assets directories.

**Comment by zezo357** [comment]
I don't exactly remember the implementation of the function, but I will let you know when it's updated

**Comment by fixatd** [comment]
No worries, in the mean time I've just forked the repo and used a modified version of those functions. Seems to be working now.

**Comment by zezo357** [comment]
Feel free to open a pr, it will help me to introduce a new interface

**Comment by fixatd** [comment]
I ended up just creating a method outside of the library based on the helper functions, since I all I really needed was to load things based on the absolute paths that I have. If anyone is interested in using it to load their model and label files, you can use this as reference:

```dart
Future<ModelObjectDetection> loadObjectDetectionModel(
  String modelPath,
  String labelPath,
  int modelWidth,
  int modelHeight,
  int numberOfClasses,
  ObjectDetectionModelType type,
) async {
  List<String> labels = await File(labelPath).readAsLines();

  int index = await ModelApi().loadModel(
    modelPath,
    numberOfClasses,
    modelWidth,
    modelHeight,
    ObjectDetectionModelType.yolov8.index,
  );

  return ModelObjectDetection(index, modelWidth, modelHeight, labels);
}
```

and it gets called thusly:

```dart

String _modelPath = "/data/user/0/package-name/app_flutter/model-file.torchscript"
String _labelPath = "/data/user/0/package-name/app_flutter/labelmap.txt";
int numberOfClasses = 1;

ModelObjectDetection _objectModelYoloV8 = await loadObjectDetectionModel(
        _modelPath,
        _labelPath,
        modelWidth,
        modelHeight,
        numberOfClasses,
        ObjectDetectionModelType.yolov8,
);
```

**Comment by abdelaziz-mahdy** [comment]
hello i am publishing new update in which based on model location value it will get absolute path or not 
<img width="515" alt="image" src="https://github.com/abdelaziz-mahdy/pytorch_lite/assets/25157308/8c7419d2-256b-4514-a2c0-8b7443c91c76">

it will be 4.2.5 

dont think you will need to change your code but i am just letting you know

**Comment by Spritan** [comment]
@abdelaziz-mahdy  how to load labelPath is similar way with modelLocation: ModelLocation.path modelis loading in successfull but what to do about labels

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy  how to load labelPath is similar way with modelLocation: ModelLocation.path modelis loading in successfull but what to do about labels

Oh, that can be updated too to have that choice

**Comment by Spritan** [comment]
> h, that can be updated too to have that choice

that would be great mean while let me try @fixatd 's approach
