### ISSUE TITLE
Any idea to increase FPS?

### ISSUE THREAD

**Issue by KingWu** [zezo357/pytorch_lite#7]
@zezo357  Run the yolov5s model with camera example. FPS ~1.4 for my phone

The spec for my phone
https://www.gsmarena.com/xiaomi_mi_11-10656.php

Any idea to optimize the speed? The slow reason because of the input size of camera image?

**Comment by zezo357** [comment]
I had the same results but I am assuming the bad fps is from the model itself 


I found an optimization repository before I will search for it and send it

**Comment by zezo357** [comment]
Guide to increase performance
https://dicksonneoh.com/portfolio/supercharging_yolov5_180_fps_cpu/

**Comment by KingWu** [comment]
@zezo357 Awesome. Try Try

**Comment by KingWu** [comment]
@zezo357 Can you success to output the optimized yolov5s. I tried to use `zoo` models

zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94 to export. But, the yolov5 seem change the logic internal. It throws error to export.

Then, spend one day to download coco dataset to train it. Also, throw errors when training it = =|||

```
ile "/Users/ycy101/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 774, in _create_named_layers_and_params
    return super()._create_named_layers_and_params(module)
  File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 532, in _create_named_layers_and_params
    params_strict=True,
  File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/utils/helpers.py", line 902, in get_named_layers_and_params_by_regex
    validate_all_params_found(param_names, found_param_names)
  File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/utils/helpers.py", line 950, in validate_all_params_found
    name_or_regex, found_param_names, name_or_regex_patterns
RuntimeError: All supplied parameter names or regex patterns not found.No match for model.9.m.0.cv2.conv.weight in found parameters ['model.7.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight', 'model.18.conv.weight', 'model.20.cv2.conv.weight', 'model.20.cv3.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv2.conv.weight', 'model.23.cv3.conv.weight', 'model.23.m.0.cv2.conv.weight']. 
Supplied ['model.23.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv3.conv.weight', 'model.23.cv2.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.18.conv.weight', 'model.9.m.0.cv2.conv.weight', 'model.7.conv.weight', 'model.20.cv3.conv.weight', 'model.20.cv2.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight']
```

If you success to generate the output, can you share it into your example?

**Comment by zezo357** [comment]
> @zezo357 Can you success to output the optimized yolov5s. I tried to use `zoo` models
> 
> zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94 to export. But, the yolov5 seem change the logic internal. It throws error to export.
> 
> Then, spend one day to download coco dataset to train it. Also, throw errors when training it = =|||
> 
> ```
> ile "/Users/ycy101/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 774, in _create_named_layers_and_params
>     return super()._create_named_layers_and_params(module)
>   File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 532, in _create_named_layers_and_params
>     params_strict=True,
>   File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/utils/helpers.py", line 902, in get_named_layers_and_params_by_regex
>     validate_all_params_found(param_names, found_param_names)
>   File "/Users/kingwu/.pyenv/versions/3.7.11/lib/python3.7/site-packages/sparseml/pytorch/utils/helpers.py", line 950, in validate_all_params_found
>     name_or_regex, found_param_names, name_or_regex_patterns
> RuntimeError: All supplied parameter names or regex patterns not found.No match for model.9.m.0.cv2.conv.weight in found parameters ['model.7.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight', 'model.18.conv.weight', 'model.20.cv2.conv.weight', 'model.20.cv3.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv2.conv.weight', 'model.23.cv3.conv.weight', 'model.23.m.0.cv2.conv.weight']. 
> Supplied ['model.23.m.0.cv2.conv.weight', 'model.21.conv.weight', 'model.23.cv3.conv.weight', 'model.23.cv2.conv.weight', 'model.20.m.0.cv2.conv.weight', 'model.18.conv.weight', 'model.9.m.0.cv2.conv.weight', 'model.7.conv.weight', 'model.20.cv3.conv.weight', 'model.20.cv2.conv.weight', 'model.8.cv2.conv.weight', 'model.13.m.0.cv2.conv.weight', 'model.17.cv2.conv.weight']
> ```
> 
> If you success to generate the output, can you share it into your example?

Can you open an issue on the original repo the author may have the answer

**Comment by zezo357** [comment]
Check this issue 
https://github.com/dnth/yolov5-deepsparse-blogpost/issues/5
