### ISSUE TITLE
Error: Lite Interpreter version number does not match. The model version must be between 3 and 7 but the model version is 8 ()

### ISSUE THREAD

**Issue by willsonwill** [zezo357/pytorch_lite#8]

**Comment by zezo357** [comment]
I will update the package lite version 


Can you test it for me?

**Comment by zezo357** [comment]
u can add the updated version by using this in pubspec yaml 

```
  pytorch_lite:
    git:
      url: https://github.com/zezo357/pytorch_lite
```

if you tested it and it ran correctly tell me to push to pub.dev

**Comment by willsonwill** [comment]
Thank you.

**Comment by zezo357** [comment]
> Thank you.

I assume it worked I will push the changes to pub dev ❤️

**Comment by willsonwill** [comment]
implementation 'org.pytorch:pytorch_android_lite:1.12.1'
implementation 'org.pytorch:pytorch_android_torchvision_lite:1.12.1'

**Comment by zezo357** [comment]
> implementation 'org.pytorch:pytorch_android_lite:1.12.1' implementation 'org.pytorch:pytorch_android_torchvision_lite:1.12.1'

? yes? that is the last version i think

**Comment by zezo357** [comment]
@willsonwill 
I updated pytorch_android_lite version to 1.12.2 hope that works (last version i can find)

**Comment by zezo357** [comment]
will run some tests then publish to pub dev
